apiVersion: v1
kind: Pod
metadata:
  labels:
    run: busybox-sc-two
  name: busybox-sc-two
  namespace: task2
spec:

  volumes:
  - name:  my-vol
    persistentVolumeClaim:
      claimName: storageclassmypvc

  containers:
  - args:
    - /bin/sh
    - -c
    - sleep 3600
    image: busybox
    name: busybox-two

    volumeMounts:
    - name: my-vol
      mountPath: /etc/foo
