kind: PersistentVolume
apiVersion: v1
metadata:
  name: storageclasspv
spec:
  storageClassName: csi-hostpath-sc
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
    - ReadWriteMany
  hostPath:
    path: /etc/foo
