kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: storageclassmypvc
  namespace: task2
spec:
  storageClassName: csi-hostpath-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
