apiVersion: v1
kind: Pod
metadata:
  labels:
    app: web-server
  name: web-server
  namespace: task1

spec:
    volumes:
    - name: shared-vol
      emptyDir: {}

    initContainers:
    - name: content-generator
      image: busybox
      volumeMounts:
      - name: shared-vol
        mountPath: /data

      command: [ "/bin/sh", "-c" ]
      args: [ 'echo \"Website initialized successfully!\" > /data/index.html' ]

    containers:
    - image: httpd
      name: httpd
      volumeMounts:
      - name: shared-vol
        mountPath: /var/www/html/
