kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mongodb-pvc
  namespace: lab4
  labels:
    app.kubernetes.io/name: mongodb
    app.kubernetes.io/instance: pacman
    app.kubernetes.io/component: mongodb
  finalizers:
  - kubernetes.io/pvc-protection
spec:
  storageClassName: csi-hostpath-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
