apiVersion: v1
kind: Secret
metadata:
  name: pacman-mongodb
  namespace: lab4
  labels:
    app.kubernetes.io/name: mongodb
    app.kubernetes.io/instance: pacman
    app.kubernetes.io/component: mongodb
type: Opaque
data:
  mongodb-root-password: "NENaRXBDckZkUg=="
