apiVersion: v1
kind: Service
metadata:
  name: pacman-pacman
  namespace: lab4
  labels:
    app.kubernetes.io/name: pacman
    app.kubernetes.io/instance: pacman
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30003
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: pacman
    app.kubernetes.io/instance: pacman
