apiVersion: apps/v1
kind: Deployment
metadata:
  name: pacman-pacman
  namespace: lab4
  labels:
    app.kubernetes.io/name: pacman
    app.kubernetes.io/instance: pacman
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: pacman
      app.kubernetes.io/instance: pacman
  template:
    metadata:
      labels:
        app.kubernetes.io/name: pacman
        app.kubernetes.io/instance: pacman
        name: pacman
    spec:
      containers:
        - name: pacman
          # image: "ghcr.io/shuguet/pacman:master"
          image: ghcr.io/shuguet/pacman:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          startupProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 10
            failureThreshold: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            failureThreshold: 1
            periodSeconds: 10
          readinessProbe:
            initialDelaySeconds: 5
            httpGet:
              path: /
              port: 8080
          env:
            - name: MONGO_SERVICE_HOST
              value: pacman-mongodb
            - name: MONGO_AUTH_USER
              value: root
            - name: MONGO_AUTH_PWD
              valueFrom:
                secretKeyRef:
                  key: mongodb-root-password
                  name: pacman-mongodb
            - name: MONGO_DATABASE
              value: pacman
            - name: MY_MONGO_PORT
              value: "27017"
            - name: MONGO_USE_SSL
              value: "false"
            - name: MONGO_VALIDATE_SSL
              value: "false"
            - name: MY_NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
