kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: storageclassmypvc
  namespace: lab1
spec:
  storageClassName: modified-standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
