kind: PersistentVolume
apiVersion: v1
metadata:
  name: static-pv
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/static-pv"
  persistentVolumeReclaimPolicy: Delete
