apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-pvc
  namespace: task5
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: csi-hostpath-sc
